# Generated by Django 3.1.6 on 2021-02-19 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=15)),
                ('nombre', models.CharField(max_length=15)),
                ('edad', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('denunciado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Posteo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_mascota', models.CharField(max_length=15)),
                ('animal', models.CharField(max_length=15)),
                ('edad', models.IntegerField()),
                ('descripcion', models.CharField(max_length=140)),
                ('fecha', models.DateField()),
                ('disponible', models.BooleanField()),
                ('postulantes', models.ManyToManyField(to='registro.Usuario')),
            ],
        ),
    ]
