# Generated by Django 3.1.6 on 2021-02-22 23:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posteo',
            name='postulantes',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='posteo',
            name='usuario_creador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
